# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode7.2
xcode_sdk: iphonesimulator
xcode_workspace: WebHere.xcworkspace
xcode_scheme: WebHere

install:
  - KEY_CHAIN=ios-build.keychain
  - security create-keychain -p travis $KEY_CHAIN
  # Make the keychain the default so identities are found
  - security default-keychain -s $KEY_CHAIN
  # Unlock the keychain
  - security unlock-keychain -p travis $KEY_CHAIN
  # Set keychain locking timeout to 3600 seconds
  - security set-keychain-settings -t 3600 -u $KEY_CHAIN


