language: objective-c

before_install:
- cd Example/Tests
- gem install cocoapods --no-rdoc --no-ri --no-document --quiet
- pod install
- KEY_CHAIN=ios-build.keychain
- security create-keychain -p travis $KEY_CHAIN
- security default-keychain -s $KEY_CHAIN
- security unlock-keychain -p travis $KEY_CHAIN
- security set-keychain-settings -t 3600 -u $KEY_CHAIN
- cd $TRAVIS_BUILD_DIR

xcode_workspace: WebHere.xcworkspace
xcode_scheme: WebHere
