# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c

script:
- xcodebuild test -workspace WebHere.xcworkspace -scheme AllTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
