# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode7.2

script:
  - xctool -workspace WebHere.xcworkspace -scheme WebHere -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool test -workspace WebHere.xcworkspace -scheme WebHereTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO

