language: objective-c

before_install:
- cd Example
- gem install cocoapods --no-rdoc --no-ri --no-document --quiet
- pod install
- KEY_CHAIN=osx-build.keychain
- security create-keychain -p travis $KEY_CHAIN
- security default-keychain -s $KEY_CHAIN
- security unlock-keychain -p travis $KEY_CHAIN
- security set-keychain-settings -t 3600 -u $KEY_CHAIN

xcode_workspace: WebHere.xcworkspace
xcode_scheme: libWebHere
